language: python
python:
  - "2.7"
before_install:
  - "sudo apt-get -qq update"
  # Start up xvfb so we can run Firefox headless
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - "wget -q https://ftp.mozilla.org/pub/mozilla.org/labs/jetpack/addon-sdk-1.16.tar.gz"
  - "tar xpzf jetpack-sdk-latest.tar.gz"
  - "source addon-sdk-1.16/bin/activate"
  - "sudo apt-get -qq install libxml2-dev libxslt-dev python-dev"
  - "pip install -r requirements.txt"
script: "./test.sh"
