# Config copied from
#  http://www.theautomatedtester.co.uk/blog/2012/using-travis-ci-for-building-and-testing-firefox-addons.html
# Use node_js because there are maybe more workers?
language: python
python:
  - "2.7"
addons:
  firefox: "30.0"
before_install:
  - wget -q https://ftp.mozilla.org/pub/mozilla.org/labs/jetpack/addon-sdk-1.16.tar.gz
  - tar xpzf addon-sdk-1.16.tar.gz
  - cd addon-sdk-1.16; source bin/activate; cd -
  - sudo apt-get install python-lxml
  #- pip install --user -r requirements.txt
before_script:
  - sh -e /etc/init.d/xvfb start
env:
  - DISPLAY=':99.0'
script: ./test.sh
