language: node_js
  before_script:
    - sh -e /etc/init.d/xvfb start
    - "wget -q https://ftp.mozilla.org/pub/mozilla.org/labs/jetpack/addon-sdk-1.16.tar.gz"
    - "tar xpzf addon-sdk-1.16.tar.gz"
    - "cd addon-sdk-1.16; source bin/activate; cd -"
    - "cd https-everywhere-tests"
  env:
    - DISPLAY=':99.0'
  script: cfx test
